export const mockPaints = [
  {
    id: "1",
    name: "Premium Interior White",
    category: "Interior",
    price: 45.99,
    image: "/white-paint-bucket.jpg",
    description: "High-quality interior paint with excellent coverage and durability.",
    colors: ["White", "Off-White", "Cream"],
    sizes: ["1L", "5L", "10L", "20L"],
    rating: 4.8,
    reviews: 124,
  },
  {
    id: "2",
    name: "Exterior Weather Guard",
    category: "Exterior",
    price: 62.5,
    image: "/blue-paint-bucket.jpg",
    description: "Weatherproof exterior paint with UV protection and fade resistance.",
    colors: ["Deep Blue", "Forest Green", "Charcoal Gray"],
    sizes: ["1L", "5L", "10L", "20L"],
    rating: 4.6,
    reviews: 98,
  },
  {
    id: "3",
    name: "Glossy Finish Premium",
    category: "Gloss",
    price: 55.99,
    image: "/red-gloss-paint.jpg",
    description: "Premium gloss finish paint for a shiny, elegant look.",
    colors: ["Red", "Black", "Silver"],
    sizes: ["1L", "5L", "10L"],
    rating: 4.7,
    reviews: 156,
  },
  {
    id: "4",
    name: "Matte Elegance",
    category: "Interior",
    price: 48.99,
    image: "/green-matte-paint.jpg",
    description: "Sophisticated matte finish for a modern aesthetic.",
    colors: ["Forest Green", "Olive", "Sage"],
    sizes: ["1L", "5L", "10L", "20L"],
    rating: 4.5,
    reviews: 87,
  },
  {
    id: "5",
    name: "Semi-Gloss Durability",
    category: "Gloss",
    price: 52.99,
    image: "/yellow-paint-bucket.jpg",
    description: "Semi-gloss paint ideal for kitchens and bathrooms.",
    colors: ["Sunny Yellow", "Soft Peach", "Coral Pink"],
    sizes: ["1L", "5L", "10L"],
    rating: 4.6,
    reviews: 112,
  },
  {
    id: "6",
    name: "Eco-Friendly Green",
    category: "Interior",
    price: 59.99,
    image: "/eco-friendly-paint.jpg",
    description: "Environmentally conscious paint with low VOC formula.",
    colors: ["Nature Green", "Earth Brown", "Sky Blue"],
    sizes: ["1L", "5L", "10L", "20L"],
    rating: 4.9,
    reviews: 203,
  },
]

export const mockCategories = ["Interior", "Exterior", "Gloss", "Matte", "Semi-Gloss"]
export const mockColors = ["Red", "Green", "Blue", "Yellow", "White", "Black", "Gray"]
export const mockSizes = ["1L", "5L", "10L", "20L"]

export const mockOrders = [
  {
    id: "ORD-001",
    date: "2024-01-15",
    items: 2,
    total: 125.5,
    status: "Delivered",
  },
  {
    id: "ORD-002",
    date: "2024-01-20",
    items: 1,
    total: 45.99,
    status: "Processing",
  },
]
